/**
 * dropdown options for entities on register user page
 */

export const entityTypes = [
  'M',
  'F',
  'O',
  'Minor',
  'NOT_KNOWN',
  'CORP',
  'Estate',
  'IRA',
  'LLC',
  'PARTNERSHIP',
  'SOLE-PROPRIETORSHIP',
  'TRUST'
];

export const entityScopes = [
  'Not Known',
  'Aerospace/Defense',
  'Airport',
  'Arts & Entertainment',
  'Automobiles and Parts',
  'Automotive',
  'Bank & Financial Services',
  'Bank/Financial Institution',
  'Bar',
  'Biotechnology',
  'Book Store',
  'Business Services',
  'Cause',
  'Chemicals',
  'Club',
  'Community Organization',
  'Community/Government',
  'Company',
  'Computers/Technology',
  'Concert Venue',
  'Consulting/Business Services',
  'Doctor',
  'Education',
  'Elementary School',
  'Energy/Utility',
  'Engineering/Construction',
  'Event Planning/Event Services',
  'Farming/Agriculture',
  'Food/Beverages',
  'Food/Grocery',
  'Government Organization',
  'Health/Beauty',
  'Health/Medical/Pharmaceuticals',
  'Health/Medical/Pharmacy',
  'Home Improvement',
  'Hospital/Clinic',
  'Hotel',
  'Industrials',
  'Insurance Company',
  'Internet/Software',
  'Landmark',
  'Lawyer',
  'Legal/Law',
  'Library',
  'Licensed Financial Representative',
  'Local Business',
  'Media/News/Publishing',
  'Middle School',
  'Mining/Materials',
  'Movie Theater',
  'Museum/Art Gallery',
  'Non-Governmental Organization (NGO)',
  'Non-Profit Organization',
  'Organization',
  'Outdoor Gear/Sporting Goods',
  'Pet Services',
  'Political Organization',
  'Political Party',
  'Preschool',
  'Professional Services',
  'Public Places',
  'Real Estate',
  'Religious Organization',
  'Restaurant/Cafe',
  'Retail and Consumer Merchandise',
  'School',
  'Shopping/Retail',
  'Small Business',
  'Spas/Beauty/Personal Care',
  'Sports Venue',
  'Sports/Recreation/Activities',
  'Telecommunication',
  'Tours/Sightseeing',
  'Train Station',
  'Transport/Freight',
  'Transportation',
  'Travel/Leisure',
  'University',
];

export const states = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
];
